server:
  port: 8088
spring:
  main:
      allow-bean-definition-overriding: true
  application:
    name: sage-mall-web
  redis:
    host: 59.110.63.47
    port: 6379
    timeout: 0
    database: 0
    password: node1199629
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 100ms
  messages:
    basename: i18n/message
    encoding: GBK

jwt:
  secret: dls
  expiration: 18000000
  header: Authorization
dubbo:
  application:
    id: sage-mall-web
    version: 1.0.0
    register-consumer: true
  protocol:    #Dubbo 服务暴露的协议配置，其中子属性 name 为协议名称，port 为协议端口（ -1 表示自增端口，从 20880 开始）
    name: dubbo
    port: -1  #dubbo协议缺省端口为20880，rmi协议缺省端口为1099，http和hessian协议缺省端口为80；如果没有配置port，则自动采用默认端口，如果配置为-1，则会分配一个没有被占用的端口。Dubbo 2.4.0+，分配的端口在协议缺省端口的基础上增长，确保端口段可控
  registry:
    #其中前缀spring-cloud说明：挂载到 Spring Cloud注册中心
    address: spring-cloud://47.95.201.250:8848  #dubbo服务注册端口，注册中心服务器地址，如果地址没有端口缺省为9090，同一集群内的多个地址用逗号分隔，如：ip:port,ip:port
    group: sage-mall
  cloud:
    subscribed-services: sage-mall-product,sage-mall-user
  scan:
    base-packages: com.dls.commom.service
logging:
  config: classpath:log4j2.xml